### ISSUE TITLE
Can we generate in bmp image format

### ISSUE THREAD

**Issue by duceretechnologies** [YPlan/treepoem#46]
Hi, Is there a way that the image can be generated in BMP format? I am trying to generate Aztec code in BMP format. 
Sorry to post this question as an issue.

**Comment by adamchainz** [comment]
`treepoem` just returns a Pillow image so you should be able to save it as bmp with `image.save('foo.bmp')` as it's [fully supported](https://pillow.readthedocs.io/en/3.4.x/handbook/image-file-formats.html#bmp).
